server:
  port: 8088

spring:
  cloud:
    stream:
      function:
        definition: purchasesProcessor
      bindings:
        purchasesProcessor-in-0:
          destination: kafka-streams-demo-transactions
        purchasesProcessor-out-0:
          destination: kafka-streams-demo-purchases
      kafka:
        streams:
          binder:
            # application-id: if_you_hava_a_single_processor
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
              commit.interval.ms: 3000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              # specific.avro.reader: true
            functions:
              purchasesProcessor:
                applicationId: spring-cloud-streams-purchasesProcessor

