/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.malsolo.kafka.streams.spring.cloud.stream.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PurchasePattern extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2836454865892400600L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PurchasePattern\",\"namespace\":\"com.malsolo.kafka.streams.spring.cloud.stream.model.avro\",\"fields\":[{\"name\":\"zipCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"item\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"date\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"amount\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<PurchasePattern> ENCODER =
      new BinaryMessageEncoder<PurchasePattern>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PurchasePattern> DECODER =
      new BinaryMessageDecoder<PurchasePattern>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PurchasePattern> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PurchasePattern> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PurchasePattern> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PurchasePattern>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PurchasePattern to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PurchasePattern from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PurchasePattern instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PurchasePattern fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String zipCode;
   private java.lang.String item;
   private java.time.LocalDate date;
   private double amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PurchasePattern() {}

  /**
   * All-args constructor.
   * @param zipCode The new value for zipCode
   * @param item The new value for item
   * @param date The new value for date
   * @param amount The new value for amount
   */
  public PurchasePattern(java.lang.String zipCode, java.lang.String item, java.time.LocalDate date, java.lang.Double amount) {
    this.zipCode = zipCode;
    this.item = item;
    this.date = date;
    this.amount = amount;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return zipCode;
    case 1: return item;
    case 2: return date;
    case 3: return amount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.DateConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: zipCode = value$ != null ? value$.toString() : null; break;
    case 1: item = value$ != null ? value$.toString() : null; break;
    case 2: date = (java.time.LocalDate)value$; break;
    case 3: amount = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'zipCode' field.
   * @return The value of the 'zipCode' field.
   */
  public java.lang.String getZipCode() {
    return zipCode;
  }


  /**
   * Sets the value of the 'zipCode' field.
   * @param value the value to set.
   */
  public void setZipCode(java.lang.String value) {
    this.zipCode = value;
  }

  /**
   * Gets the value of the 'item' field.
   * @return The value of the 'item' field.
   */
  public java.lang.String getItem() {
    return item;
  }


  /**
   * Sets the value of the 'item' field.
   * @param value the value to set.
   */
  public void setItem(java.lang.String value) {
    this.item = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.time.LocalDate getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.time.LocalDate value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Creates a new PurchasePattern RecordBuilder.
   * @return A new PurchasePattern RecordBuilder
   */
  public static com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder newBuilder() {
    return new com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder();
  }

  /**
   * Creates a new PurchasePattern RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PurchasePattern RecordBuilder
   */
  public static com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder newBuilder(com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder other) {
    if (other == null) {
      return new com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder();
    } else {
      return new com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder(other);
    }
  }

  /**
   * Creates a new PurchasePattern RecordBuilder by copying an existing PurchasePattern instance.
   * @param other The existing instance to copy.
   * @return A new PurchasePattern RecordBuilder
   */
  public static com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder newBuilder(com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern other) {
    if (other == null) {
      return new com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder();
    } else {
      return new com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder(other);
    }
  }

  /**
   * RecordBuilder for PurchasePattern instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PurchasePattern>
    implements org.apache.avro.data.RecordBuilder<PurchasePattern> {

    private java.lang.String zipCode;
    private java.lang.String item;
    private java.time.LocalDate date;
    private double amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.zipCode)) {
        this.zipCode = data().deepCopy(fields()[0].schema(), other.zipCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.item)) {
        this.item = data().deepCopy(fields()[1].schema(), other.item);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing PurchasePattern instance
     * @param other The existing instance to copy.
     */
    private Builder(com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.zipCode)) {
        this.zipCode = data().deepCopy(fields()[0].schema(), other.zipCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.item)) {
        this.item = data().deepCopy(fields()[1].schema(), other.item);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'zipCode' field.
      * @return The value.
      */
    public java.lang.String getZipCode() {
      return zipCode;
    }


    /**
      * Sets the value of the 'zipCode' field.
      * @param value The value of 'zipCode'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder setZipCode(java.lang.String value) {
      validate(fields()[0], value);
      this.zipCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'zipCode' field has been set.
      * @return True if the 'zipCode' field has been set, false otherwise.
      */
    public boolean hasZipCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'zipCode' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder clearZipCode() {
      zipCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'item' field.
      * @return The value.
      */
    public java.lang.String getItem() {
      return item;
    }


    /**
      * Sets the value of the 'item' field.
      * @param value The value of 'item'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder setItem(java.lang.String value) {
      validate(fields()[1], value);
      this.item = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'item' field has been set.
      * @return True if the 'item' field has been set, false otherwise.
      */
    public boolean hasItem() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'item' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder clearItem() {
      item = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.time.LocalDate getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder setDate(java.time.LocalDate value) {
      validate(fields()[2], value);
      this.date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder clearDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder setAmount(double value) {
      validate(fields()[3], value);
      this.amount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.spring.cloud.stream.model.avro.PurchasePattern.Builder clearAmount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PurchasePattern build() {
      try {
        PurchasePattern record = new PurchasePattern();
        record.zipCode = fieldSetFlags()[0] ? this.zipCode : (java.lang.String) defaultValue(fields()[0]);
        record.item = fieldSetFlags()[1] ? this.item : (java.lang.String) defaultValue(fields()[1]);
        record.date = fieldSetFlags()[2] ? this.date : (java.time.LocalDate) defaultValue(fields()[2]);
        record.amount = fieldSetFlags()[3] ? this.amount : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PurchasePattern>
    WRITER$ = (org.apache.avro.io.DatumWriter<PurchasePattern>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PurchasePattern>
    READER$ = (org.apache.avro.io.DatumReader<PurchasePattern>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










